language: cpp
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      - g++-5
      - pkg-config
      - libusb-1.0-0
      - libusb-1.0-0-dev
      - libftdi1-2
      - libftdi1-dev
      - libftdipp1-2v5
      - libftdipp1-dev

#before_install:
#- gcc -v

#install:
# C++11
#- sudo apt-get install -qq g++-5 libftdi1-2 libftdi1-dev libftdipp1-2 libftdipp1-dev

script:
- qmake ponyprog.pro -r -spec linux-g++-64 CONFIG+=debug QMAKE_CXX=g++-5 QMAKE_LINK=g++-5
- make

